### PR TITLE
Add Dockerfile and client.py; deploy to EC2 on AWS via Github Actions

### PR DESCRIPTION
**Pull request by abrichr**
## Instructions

1. Fork https://github.com/OpenAdaptAI/SoM, clone your fork to your local machine, and check out the feat/deploy branch.
2. Follow the instructions at the top of [deploy.py](https://github.com/OpenAdaptAI/SoM/blob/feat/deploy/deploy.py).

## Summary

This PR implements functionality to automatically deploy SoM to EC2 on AWS via Docker, Github Actions, and boto3.

It also addresses https://github.com/microsoft/SoM/issues/22 by upgrading gradio to 4.17.0 and adds a working example `client.py`.

image

```
(venv) abrichr@MacBook-Pro-4 SoM % python client.py                                                                          
Loaded as API: http://3.84.210.111:6092/ ✔         
/private/var/folders/35/pqjnmmwx24d2mtf4frt5dhcc0000gn/T/gradio/60cdba21007c18ea62202556bd944745f82a4a89/image.png
```

### CODE REVIEW

**Comment by abrichr** [comment]
@microsoft-github-policy-service agree

**Comment by abrichr** [comment]
@jwyang @FengLi-ust @MaureenZOU @microsoftopensource @HaoZhang534 @eltociear thank you for the excellent work on this repo!

I believe this PR is ready to merge. Please let me know if you have any questions/comments!

**Comment by jwyang** [comment]
Thank you so much for the great effort! @abrichr. Sorry for getting back lately. I left a quick comment above, let's move quickly to merge your PRs.

**Comment by abrichr** [comment]
Thank you @jwyang!

> I left a quick comment above

I am unable to find it, perhaps it's in a review that hasn't yet been submitted? 🙏

**Comment by jwyang** [comment]
@abrichr 

image

**Comment by abrichr** [comment]
Thanks @jwyang! (It looks like that comment is still "Pending", which means others won't see it until the review has been submitted -- see https://github.com/orgs/community/discussions/10369).

The `gradio` version is specified in the Dockerfile: https://github.com/microsoft/SoM/pull/19/files#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R31

```
&& pip install gradio==4.17.0
```

Please let me know if I can clarify anything further! 🙏

**Comment by jwyang** [comment]
oh, my bad, @abrichr, then I think everything looks great!

**Pull request merged**
